package com.mknlabs.expensetracker.domain.repository

import com.mknlabs.expensetracker.models.InstallmentOccurrence
import com.mknlabs.expensetracker.models.InstallmentPlan
import com.mknlabs.expensetracker.models.RecurringTransactionRule
import kotlinx.coroutines.flow.Flow

interface RecurringRuleRepository {
    fun observeActiveRecurringRules(): Flow<List<RecurringTransactionRule>>

    suspend fun getActiveRules(): List<RecurringTransactionRule>

    suspend fun getActiveByTransactionId(transactionId: String): RecurringTransactionRule?

    suspend fun upsertRule(rule: RecurringTransactionRule): RecurringTransactionRule

    suspend fun setEnabled(id: String, enabled: Boolean)

    suspend fun setNotificationsEnabled(id: String, enabled: Boolean)

    suspend fun deleteRule(id: String)

    // ── Installment (EMI) plan ──────────────────────────────────────────────

    /** Scheduled installments of a rule, in plan order. */
    fun observeOccurrences(ruleId: String): Flow<List<InstallmentOccurrence>>

    /**
     * Every live occurrence across all rules — for screens that show several
     * plans at once (recurring list progress). Group by [InstallmentOccurrence.ruleId].
     */
    fun observeAllOccurrences(): Flow<List<InstallmentOccurrence>>

    suspend fun getOccurrences(ruleId: String): List<InstallmentOccurrence>

    /**
     * Derived progress for a rule's plan, or null when the rule carries no plan
     * (every REGULAR rule, including all legacy ones).
     */
    suspend fun getInstallmentPlan(ruleId: String): InstallmentPlan?

    /**
     * Attach an EMI plan to an EXISTING rule, converting it from REGULAR to
     * INSTALLMENT. The template transaction, the rule's schedule, and every
     * transaction already generated by it are left untouched, so a user can turn
     * a live recurring rule into a loan without losing history.
     *
     * Idempotent and reversible: installments are materialized at deterministic
     * slot ids, so any slot that already exists (including one soft-deleted by a
     * previous [convertToRegular]) is revived with its paid state, amount and
     * linked transaction intact.
     *
     * Converting a REGULAR rule that has already charged part of its series
     * resumes the plan over those payments instead of restarting it: the plan
     * keeps the series' own start date and adopts each occurrence already
     * recorded as a settled installment, so a rule with 4 of its 8 occurrences
     * behind it shows 4 of 8 rather than 0 of 8 dated from today. While resuming,
     * the series' own dates win and [firstDueAt] is ignored; a rule with nothing
     * charged yet starts the plan at [firstDueAt] exactly as before.
     *
     * @return the updated rule, or null if [ruleId] no longer exists.
     */
    suspend fun convertToInstallment(
        ruleId: String,
        totalAmountMinor: Long,
        installmentAmountMinor: Long,
        totalInstallments: Int,
        firstDueAt: Long
    ): RecurringTransactionRule?

    /**
     * Strip the EMI plan from a rule, converting it back to REGULAR. The plan
     * terms are retained (inert while the rule is REGULAR) and the installment
     * schedule is soft-deleted rather than erased, so converting back restores
     * the same plan with no data loss.
     *
     * @return the updated rule, or null if [ruleId] no longer exists.
     */
    suspend fun convertToRegular(ruleId: String): RecurringTransactionRule?

    // ── Installment (EMI) mutations ─────────────────────────────────────────

    /**
     * Settle a single installment, covering pay / early pay / late pay /
     * retroactive pay with one operation: legal on any PENDING slot regardless
     * of its due date — [paidAt] only records when the payment happened.
     *
     * Creates the expense transaction from the rule's template (deterministic
     * id = the slot id, slot amount, [paidAt] as its date), links it on the
     * occurrence, and marks the plan COMPLETED on the rule once every
     * installment is paid. The template transaction is never modified.
     *
     * Idempotent: a slot that is missing, soft-deleted, or already settled
     * returns null and creates no transaction. [InstallmentOccurrenceStatus.OVERDUE]
     * is never stored — it stays a derived view of a past-due PENDING slot.
     *
     * @return the updated occurrence, or null when nothing was paid.
     */
    suspend fun payInstallment(
        occurrenceId: String,
        paidAt: Long = System.currentTimeMillis()
    ): InstallmentOccurrence?

    /**
     * Settle several installments in one user action (multi-pay sheet). Each
     * slot goes through [payInstallment], so already-settled slots are simply
     * skipped.
     *
     * @return how many slots actually transitioned to PAID.
     */
    suspend fun payInstallments(occurrenceIds: List<String>, paidAt: Long): Int

    /**
     * Adopt an already-recorded transaction as the settlement of [occurrenceId].
     *
     * Used when a plan is created *together with* its first payment: the Add
     * Transaction screen has already saved the transaction that the user means as
     * installment #1, so unlike [payInstallment] nothing is created here — the
     * slot is only linked to it (and the plan's tracked due date, remaining count
     * and completion follow the ledger as usual). Without this, an EMI created
     * with a first due date on the transaction's own date would be paid twice:
     * once by the transaction the user entered and again by the worker's due
     * reconciliation for the same slot.
     *
     * Idempotent like the other mutations: a slot that is missing, soft-deleted or
     * already settled is left untouched.
     *
     * @return the updated occurrence, or null when nothing changed.
     */
    suspend fun settleOccurrenceWithTransaction(
        occurrenceId: String,
        transactionId: String,
        paidAt: Long
    ): InstallmentOccurrence?

    /**
     * Mark a PENDING installment as deliberately skipped: no transaction is
     * created and the amount stays owed on the plan's remaining balance.
     *
     * @return the updated occurrence, or null when the slot is not PENDING.
     */
    suspend fun skipInstallment(occurrenceId: String): InstallmentOccurrence?

    /**
     * Return a PAID or SKIPPED installment to PENDING. When undoing a payment,
     * the transaction that slot generated is soft-deleted so the ledger mirrors
     * the undo — never the template, never another slot's transaction.
     *
     * @return the updated occurrence, or null when the slot is not settled.
     */
    suspend fun undoInstallment(occurrenceId: String): InstallmentOccurrence?

    /**
     * Worker entry point: pay every PENDING slot of an installment rule whose
     * due date has passed ([dueAt] <= [now]), each recorded at its own due
     * date. Slots already settled are skipped, so repeated runs are free.
     *
     * @return the notes of the transactions created, for the recurring-updated
     * notification (empty when nothing was due).
     */
    suspend fun reconcileDueInstallments(ruleId: String, now: Long): List<String>
}
